name: Add E2E Label to PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels to PR
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }} --add-label Run Smoke E2E
