name: Create E2E tag for PR

on:
  pull_request:
    types: [labeled]

jobs:
  create-pr-e2e-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - name: Install Axios
        run: yarn add axios

      - name: Install dependencies
        run: yarn --immutable

      # - name: Create E2E tag for PR
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: yarn run create-pr-e2e-tag

      - name: Create a Git tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a e2e-pr-7339 -m "E2E tag for triggering Bitrise E2E build"
          git push origin e2e-pr-7339
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# name: Bitrise E2E

# on:
#   pull_request:
#     types: [labeled]

# jobs:
#   deploy:
#     name: Run e2e smoke test on Bitrise
#     runs-on: ubuntu-latest
#     steps:
#       - name: Start pr_smoke_e2e_pipeline workflow in Bitrise
#         if: contains(github.event.pull_request.labels.*.name, 'needs-smoke-e2e')
#         run: |
#           curl https://app.bitrise.io/app/${{ secrets.BITRISE_APP_ID }}/build/start.json -L -H 'Content-Type: application/json' --data '{
#             "hook_info": {
#               "type": "bitrise",
#               "build_trigger_token": "${{ secrets.BITRISE_BUILD_TRIGGER_TOKEN }}"
#             },
#             "build_params": {
#               "branch": "${{ github.head_ref }}",
#               "pipeline_id": "pr_smoke_e2e_pipeline"
#             },
#             "triggered_by": "curl"
#           }'
