name: E2E Merge Queue Check

on:
  push:
    branches: main
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  apply-smoke-label:
    runs-on: ubuntu-latest
    steps:
      - name: Apply "Run Smoke E2E" label
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels
          labels: 'Run Smoke E2E'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-e2e-check:
    runs-on: ubuntu-latest
    needs: apply-smoke-label
    uses: ./.github/workflows/bitrise-e2e-check.yml  # Reuse the Bitrise check workflow
    with:
      pr_number: ${{ github.event.number || github.event.pull_request.number }}
      e2e_label: 'Run Smoke E2E'
      e2e_pipeline: 'pr_smoke_e2e_pipeline'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BITRISE_BUILD_TRIGGER_TOKEN: ${{ secrets.BITRISE_BUILD_TRIGGER_TOKEN }}
      BITRISE_APP_ID: ${{ secrets.BITRISE_APP_ID }}
