name: Run Bitrise E2E

on:
  pull_request:
    types: [labeled]

jobs:
  run-bitrise-e2e:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - name: Install Axios
        run: yarn add axios

      - name: Install dependencies
        run: yarn --immutable

      - name: Run Bitrise E2E
        env:
          BITRISE_BUILD_TRIGGER_TOKEN: ${{ secrets.BITRISE_BUILD_TRIGGER_TOKEN }}
          BITRISE_APP_ID: 'be69d4368ee7e86d'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run run-bitrise-e2e
